name: BrainDoc
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.7
  page_transition: ^2.1.0
  pin_code_fields: ^8.0.1
  rename: ^3.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/languages/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/theming/
  filename: assets.dart

# use this command to run the package >> flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash_android12.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/splash_android12.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/splash_android12.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/splash_android12.png"

# use this command to run the package >> dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  color_dark: "#ffffff"
  android: true
  ios: true
  web: false
  android_12:
    image: assets/images/splash_android12.png
    color: "#ffffff"
